console.log("running the main action for failure");